sudo: required
services:
  - docker

before_install:
  - docker build -t erikbcode/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true erikbcode/react-test npm run test

after_success:
  - docker build -t erikbcode/multi-client ./client
  - docker build -t erikbcode/multi-nginx ./nginx
  - docker build -t erikbcode/multi-server ./server
  - docker build -t erikbcode/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push erikbcode/multi-client
  - docker push erikbcode/multi-nginx
  - docker push erikbcode/multi-server
  - docker push erikbcode/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  environment: "Multi-docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-868246842734"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
