version: '3'
services: 
  client:
    image: "erikbcode/multi-client"
    hostname: client
    mem_limit: 128m
  server:
    image: "erikbcode/multi-server"
    hostname: api
    mem_limit: 128m
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "erikbcode/multi-worker"
    hostname: worker
    mem_limit: 128m
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "erikbcode/nginx"
    hostname: nginx
    mem_limit: 128m
    ports: 
    - "80:80"
  